apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "backstage.f5.demo"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backstage-np
            port:
              number: 80