apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: ducthanh1989/backstage:v2805
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 7007
        envFrom:
          - secretRef:
              name: postgres-secrets
          - secretRef:
              name: backstage-secrets
        resources:
          limits:
            cpu: 2
            memory: 2.0Gi
        # readinessProbe:
        #   httpGet:
        #     port: 7000
        #     path: /healthcheck
        # livenessProbe:
        #   httpGet:
        #     port: 7000
        #     path: /healthcheck